# Generated by Django 4.1.7 on 2023-03-03 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_malicious_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_messages',
            options={'verbose_name': 'Users_message', 'verbose_name_plural': 'Users_messages'},
        ),
        migrations.AlterField(
            model_name='users_messages',
            name='senders_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
